//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudApiDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_emp_data
    {
        
        public int Id { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public string City { get; set; }
        public string Dept_Name { get; set; }
        public string Designation { get; set; }
    }
}
